### ISSUE TITLE
Adding more fields would be great

### ISSUE THREAD

**Issue by wirtsi** [karust/openserp#3]
I would be quite interested in additional fields from Google, eg

* Anwer Box
* Organic Results (right now I assume it mixes organic and paid?)

Bests & thanks

**Comment by karust** [comment]
I'll keep that in mind for future updates!
For now, all results are mixed and the answer box is omitted.

**Comment by karust** [comment]
Implemented in release [0.3] (https://github.com/karust/openserp/releases/tag/v0.3)
* Now you can add answers to results using the `answers` query parameter, e.g.: `http://127.0.0.1:7000/google/search?text=privatschule zürich&limit=50&answers=true`.
* Ads will be marked in results, e.g. `"ad": true`.

**Comment by wirtsi** [comment]
A remark here would be that the results are not sorted by rank. I get rank 1 and 2 as first hits, then there is -1, -2, -3, -4 and then it goes to 3 again. Not a biggie but seems a bit weird

**Comment by karust** [comment]
Yeah, I guess the other way could be to use some kind of tag like `"answer": true` or return them as a separate entity. 
But I didn't want the answers to interfere with other result rankings and change the API much, so I left with this option

**Comment by wirtsi** [comment]
No sweat, just wanted to mention this. Thanks for the feature, already testing if I can get rid of Tavily now ;)
